apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: descent
resources:
  - namespace.yaml
  - rbac.yaml
  - service.yaml
  - gateway.yaml
  - content.yaml
  - networkpolicy.yaml
