// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SourceSharp.Host.Data;

#nullable disable

namespace SourceSharp.Host.Data.Migrations
{
    [DbContext(typeof(HostDbContext))]
    partial class HostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SourceSharp.Host.Data.AccountRow", b =>
                {
                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_id");

                    b.Property<bool>("Banned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("banned");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.HasKey("SteamId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.AuditRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("after_json");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("before_json");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("At");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.AustraliumRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("character_id");

                    b.Property<long>("Delta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("delta");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("Ref")
                        .HasColumnType("TEXT")
                        .HasColumnName("ref");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("australium_ledger", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.CharacterRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("account");

                    b.Property<long>("Australium")
                        .HasColumnType("INTEGER")
                        .HasColumnName("australium");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("class_name");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deleted");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("difficulty");

                    b.Property<bool>("Fallen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fallen");

                    b.Property<bool>("Hardcore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hardcore");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ReachedDepth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reached_depth");

                    b.Property<byte[]>("Sheet")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("sheet");

                    b.Property<int>("SheetVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sheet_version");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<long>("Xp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("Account");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.IdempotencyRow", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<byte[]>("Response")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("response");

                    b.HasKey("RequestId");

                    b.HasIndex("At");

                    b.ToTable("idempotency", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.InstanceRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long?>("Booted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("booted");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<long?>("DrainAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("drain_at");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exit_code");

                    b.Property<int>("ExpectedPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expected_port");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<long?>("LastHeartbeat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_heartbeat");

                    b.Property<string>("LevelHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("level_hash");

                    b.Property<long?>("LiveAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("live_at");

                    b.Property<string>("ModImage")
                        .HasColumnType("TEXT")
                        .HasColumnName("mod_image");

                    b.Property<string>("ModImageDigest")
                        .HasColumnType("TEXT")
                        .HasColumnName("mod_image_digest");

                    b.Property<string>("PartyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("party_id");

                    b.Property<int>("Players")
                        .HasColumnType("INTEGER")
                        .HasColumnName("players");

                    b.Property<string>("PodIp")
                        .HasColumnType("TEXT")
                        .HasColumnName("pod_ip");

                    b.Property<string>("PodName")
                        .HasColumnType("TEXT")
                        .HasColumnName("pod_name");

                    b.Property<string>("PodUid")
                        .HasColumnType("TEXT")
                        .HasColumnName("pod_uid");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<long?>("ReapedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reaped_at");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("RulesSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("rules_sha256");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("PodName");

                    b.HasIndex("State");

                    b.ToTable("instances", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.ItemEventRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER")
                        .HasColumnName("at");

                    b.Property<string>("FromOwner")
                        .HasColumnType("TEXT")
                        .HasColumnName("from_owner");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("ToOwner")
                        .HasColumnType("TEXT")
                        .HasColumnName("to_owner");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("item_events", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.ItemRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("AdminEdited")
                        .HasColumnType("INTEGER")
                        .HasColumnName("admin_edited");

                    b.Property<string>("BaseType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("base_type");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<string>("ForCharacter")
                        .HasColumnType("TEXT")
                        .HasColumnName("for_character");

                    b.Property<bool>("Identified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("identified");

                    b.Property<byte[]>("Instance")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("instance");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_level");

                    b.Property<long>("MintedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minted_at");

                    b.Property<string>("MintedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("minted_by");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("owner_kind");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rarity");

                    b.Property<int>("RolledForLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rolled_for_level");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<long?>("TerminalAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("terminal_at");

                    b.Property<string>("TerminalReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("terminal_reason");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tier");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BaseType");

                    b.HasIndex("Rarity");

                    b.HasIndex("InstanceId", "State");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.LeaseRow", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("character_id");

                    b.Property<long>("Expires")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expires");

                    b.Property<long>("Heartbeat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heartbeat");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<long>("Issued")
                        .HasColumnType("INTEGER")
                        .HasColumnName("issued");

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("token");

                    b.HasKey("CharacterId");

                    b.HasIndex("InstanceId");

                    b.ToTable("leases", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.LevelClaimRow", b =>
                {
                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("character_id");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<long>("LastUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_used");

                    b.Property<string>("LevelHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("level_hash");

                    b.Property<long>("Since")
                        .HasColumnType("INTEGER")
                        .HasColumnName("since");

                    b.HasKey("CharacterId", "Depth");

                    b.HasIndex("LevelHash");

                    b.ToTable("character_levels", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.LevelRow", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("difficulty");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<string>("HandedTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("handed_to");

                    b.Property<long>("PackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pack_id");

                    b.Property<string>("RulesSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("rules_sha256");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<string>("Tileset")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tileset");

                    b.HasKey("Hash");

                    b.HasIndex("Depth", "PackId", "State");

                    b.ToTable("levels", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.LostAndFoundRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("character_id");

                    b.Property<long>("Fee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fee");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<string>("OriginInstance")
                        .HasColumnType("TEXT")
                        .HasColumnName("origin_instance");

                    b.Property<long>("Since")
                        .HasColumnType("INTEGER")
                        .HasColumnName("since");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("lost_and_found", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.MapJobRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<long?>("Finished")
                        .HasColumnType("INTEGER")
                        .HasColumnName("finished");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT")
                        .HasColumnName("log");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<long?>("Started")
                        .HasColumnType("INTEGER")
                        .HasColumnName("started");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("State", "Priority");

                    b.ToTable("map_jobs", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.PackAssignmentRow", b =>
                {
                    b.Property<string>("Mod")
                        .HasColumnType("TEXT")
                        .HasColumnName("mod");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth");

                    b.Property<long>("AssignedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_by");

                    b.Property<int>("OldLevels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("old_levels");

                    b.Property<long>("PackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pack_id");

                    b.Property<bool>("Pinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pinned");

                    b.HasKey("Mod", "Depth");

                    b.ToTable("pack_assignments", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.PackRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.Property<string>("Library")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("library");

                    b.Property<string>("LibraryVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("library_version");

                    b.Property<string>("LintJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("lint_json");

                    b.Property<string>("Mod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mod");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PackId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pack_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<long>("UploadedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Mod", "Library", "Version")
                        .IsUnique();

                    b.ToTable("packs", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.PartyMemberRow", b =>
                {
                    b.Property<string>("PartyId")
                        .HasColumnType("TEXT")
                        .HasColumnName("party_id");

                    b.Property<string>("CharacterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("character_id");

                    b.Property<bool>("Invited")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invited");

                    b.Property<long>("Since")
                        .HasColumnType("INTEGER")
                        .HasColumnName("since");

                    b.HasKey("PartyId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("party_members", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.PartyRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<string>("Leader")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("leader");

                    b.HasKey("Id");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.PlayerRow", b =>
                {
                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_id");

                    b.Property<string>("Allocator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("allocator");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen");

                    b.Property<string>("PinnedPeer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pinned_peer");

                    b.Property<string>("PreviousJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_json");

                    b.Property<long>("Since")
                        .HasColumnType("INTEGER")
                        .HasColumnName("since");

                    b.HasKey("SteamId");

                    b.HasIndex("PinnedPeer");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.RulesModuleRow", b =>
                {
                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<string>("Assembly")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assembly");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contract_version");

                    b.Property<string>("DepsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("deps_json");

                    b.Property<string>("FirstInstance")
                        .HasColumnType("TEXT")
                        .HasColumnName("first_instance");

                    b.Property<long>("FirstSeen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_seen");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Sha256");

                    b.ToTable("rules_modules", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.SessionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Backend")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("backend");

                    b.Property<string>("ClientAddr")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_addr");

                    b.Property<string>("CloseReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("close_reason");

                    b.Property<long?>("IdentifiedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("identified_at");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_id");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_seen");

                    b.Property<long>("Opened")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opened");

                    b.Property<string>("Peer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("peer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("SteamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("steam_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientAddr");

                    b.HasIndex("Peer");

                    b.HasIndex("SteamId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Key");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.TradeRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("A")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("a");

                    b.Property<string>("B")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("b");

                    b.Property<long?>("Committed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("committed");

                    b.Property<bool>("ConfirmedA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirmed_a");

                    b.Property<bool>("ConfirmedB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("confirmed_b");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created");

                    b.Property<string>("HubInstance")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hub_instance");

                    b.Property<bool>("LockedA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("locked_a");

                    b.Property<bool>("LockedB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("locked_b");

                    b.Property<string>("OfferJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("offer_json");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("HubInstance", "State");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("SourceSharp.Host.Data.VendorStockRow", b =>
                {
                    b.Property<string>("HubInstance")
                        .HasColumnType("TEXT")
                        .HasColumnName("hub_instance");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<long>("RolledAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rolled_at");

                    b.HasKey("HubInstance", "Vendor", "ItemId");

                    b.ToTable("vendor_stock", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
